### PR TITLE
Hack together a basic demo of Quick Account

### PR DESCRIPTION
**Pull request by ryachart**
When inviting friends to try Algorand, it's always a bit of an ordeal to explain to them the big warning screen about their pass phrase, private keys, and what this all means when I'm just trying to pay them 20 Algos to settle up for lunch.

Inspired by a [reddit thread](https://www.reddit.com/r/AlgorandOfficial/comments/p6w6l2/adoption_idea_algo_tips/h9fo11b?utm_source=share&utm_medium=web2x&context=3), I decided to see how hard this was to put together for iOS.

### CODE REVIEW

**Comment by ian-algorand** [comment]
This is really cool! We'll definitely take this into consideration. I really like the idea of a quick account. Although we'll need to make sure that once they create this account, we warn them repeatedly to back-up their passphrase. 

But yea, very do-able. Thanks for the suggestion!

**Comment by ryachart** [comment]
Thanks for checking it out.

The Algorand Wallet mobile app feels like the front door of the Algorand economy. The trade offs of security versus easing that funnel arent simple concerns. Good luck =)

**Comment by barnjamin** [comment]
I still want this 🙏

**Comment by yigitguler** [comment]
This feature is finally live!

**Pull request closed without merging**
